### ISSUE TITLE
Technical analysis is cringe and a scam

### ISSUE THREAD

**Issue by kevinheavey** [gregyjames/Panther#1]
Firstly, this is a really cool library and some of it (SMA and EMA) is useful for things that aren't technical analysis.

Secondly, you're clearly a smart guy and I can see you're interested in other quant trading and quant finance stuff. I would encourage you to focus on those things instead, because they are actually useful and won't be embarrassing like TA is. And also because the existence of a high-performance TA library like this serves to legitimize TA.

**Comment by pro465** [comment]
why is TA not useful? I think people do not need to work on the things you would like them to.

**Comment by kevinheavey** [comment]
> why is TA not useful? I think people do not need to work on the things you would like them to.

Because it's financial astrology.  The people peddling it are predominantly liars and schmucks. These people use it to say whatever they want because TA doesn't give you falsifiable predictions, it just gives you ways to draw weird lines on a chart.

The guy who made this library is a smart college student and I'm encouraging him to focus his efforts on things that aren't scams and won't make him sound like an idiot in a job interview at a quant trading firm.

**Comment by pro465** [comment]
um well then i guess you are a teacher/parent and would not interfere, unless, you are just a random dude that just does not want to see TA anywhere he goes...

**Comment by pro465** [comment]
also, TA is not just limited to finance. i am not a finance guy, yet i have heard of TA being used to do many other things. so no, just let him do whatever he wants. it does not mean it is not gonna be useful outside of your so called 'astrology'.

if you really want to make him stop this, do the same to Panda.

**Comment by kevinheavey** [comment]
Yeah you can do whatever you want with TA since it's nonsense to begin with.

I can't parse the other things you're saying

**Comment by pro465** [comment]
ok good i guess, since that means we dont have to argue anymore
