### ISSUE TITLE
How to rename the compiled code released on MAC with M1 chip?

### ISSUE THREAD

**Issue by jeffrey82221** [gregyjames/Panther#3]
Hi, 

I run the `cargo build --release` script from the main directory, and `libpanther.d` and `libpanther.dylib` are created in the `release` folder along with many `*.d` and `*.dylib` files in the `build` and `deps` folder. How do I rename those files such that they can work with my python script? 

Any suggestions?

**Comment by Franky1** [comment]
I am not familiar with Mac. But i tried it with Linux.
Is there a `target/release/libpanther.so` ?
If yes, rename `libpanther.so` to `panther.so` and try it with the python examples under `/speed_tests` again.
If not, try the same with the `libpanther.dylib` file.

**Comment by gregyjames** [comment]
@Franky1 I only tested this in windows, so if you could successfully build the library on Linux and get it working, I would appreciate if you could add the steps to the Readme

**Comment by Franky1** [comment]
I tried it out in **Docker** and made a multistage Dockerfile.
I think that on a desktop Linux - if you have a working Rust toolchain running - it should work just like on Windows, except that the generated lib is called `libpanther.so`
Unless there are any dependencies that you might have to install in connection with PyO3, I'm not familiar with Rust and PyO3 at all...

**Comment by Franky1** [comment]
@jeffrey82221
I think you should use the `libpanther.dylib` file, this should be the dynamic library extension on macOS.
Try to rename it to `panther.dylib` or `panther.so` and try the python examples.

**Comment by messense** [comment]
@gregyjames Checkout [maturin](https://github.com/PyO3/maturin) and [maturin-action](https://github.com/messense/maturin-action), they should help you package this library into Python wheels and then you can distribute them on PyPI.

**Comment by gregyjames** [comment]
@messense Thanks for this! I'll change the name and upload the wheels so nobody else gets this issue
